using Ocelot.Filter;
using System.Text.Json;

namespace Ocelot.UnitTests.Filter
{
    public class HttpStatusCodeFilterTests : UnitTest
    {
        [Theory]
        [InlineData(new HttpStatusCode[] { HttpStatusCode.OK, HttpStatusCode.Forbidden }, HttpStatusCode.OK, true)]
        [InlineData(new HttpStatusCode[] { HttpStatusCode.OK, HttpStatusCode.Forbidden }, HttpStatusCode.Forbidden, true)]
        [InlineData(new HttpStatusCode[] { HttpStatusCode.OK, HttpStatusCode.Forbidden }, HttpStatusCode.InternalServerError, false)]
        [InlineData(null, HttpStatusCode.OK, true)] // a null whitelist means "everything is whitelisted"
        [InlineData(null, HttpStatusCode.InternalServerError, true)] // a null whitelist means "everything is whitelisted"
        [InlineData(new HttpStatusCode[] { }, HttpStatusCode.OK, false)] // an empty whitelist means "nothing is whitelisted"
        public void Whitelisting_with_HttpStatusCodes(HttpStatusCode[] whitelist, HttpStatusCode statusCode, bool shouldPass)
        {
            HttpStatusCodeFilter filter = new HttpStatusCodeFilter(FilterType.Whitelist, whitelist);
            Assert.True(filter.PassesFilter(statusCode) == shouldPass);
        }

        [Theory]
        [InlineData(new HttpStatusCode[] { HttpStatusCode.OK, HttpStatusCode.Forbidden }, HttpStatusCode.OK, false)]
        [InlineData(new HttpStatusCode[] { HttpStatusCode.OK, HttpStatusCode.Forbidden }, HttpStatusCode.Forbidden, false)]
        [InlineData(new HttpStatusCode[] { HttpStatusCode.OK, HttpStatusCode.Forbidden }, HttpStatusCode.InternalServerError, true)]
        [InlineData(null, HttpStatusCode.OK, false)] // a null blacklist means "everything is blacklisted"
        [InlineData(null, HttpStatusCode.InternalServerError, false)] // a null blacklist means "everything is blacklisted"
        [InlineData(new HttpStatusCode[] { }, HttpStatusCode.OK, true)] // an empty whitelist means "nothing is blacklisted"
        public void Blacklisting_with_HttpStatusCodes(HttpStatusCode[] blacklist, HttpStatusCode statusCode, bool shouldPass)
        {
            HttpStatusCodeFilter filter = new HttpStatusCodeFilter(FilterType.Blacklist, blacklist);
            Assert.True(filter.PassesFilter(statusCode) == shouldPass);
        }

        [Theory]
        [InlineData(new string[] { "200", "403" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "200", "403" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "200", "403" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(null, HttpStatusCode.OK, true)] // a null whitelist means "everything is whitelisted"
        [InlineData(null, HttpStatusCode.InternalServerError, true)] // a null whitelist means "everything is whitelisted"
        [InlineData(new string[] { }, HttpStatusCode.OK, false)] // an empty whitelist means "nothing is whitelisted"

        #region Are codes included in the correct ranges and therefore whitelisted?
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Continue, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.SwitchingProtocols, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Processing, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.EarlyHints, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Created, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Accepted, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NonAuthoritativeInformation, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NoContent, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ResetContent, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PartialContent, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MultiStatus, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.AlreadyReported, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.IMUsed, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Ambiguous, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MultipleChoices, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Moved, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MovedPermanently, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Found, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Redirect, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RedirectMethod, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.SeeOther, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotModified, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UseProxy, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Unused, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RedirectKeepVerb, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.TemporaryRedirect, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PermanentRedirect, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.BadRequest, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Unauthorized, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PaymentRequired, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotFound, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MethodNotAllowed, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotAcceptable, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ProxyAuthenticationRequired, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestTimeout, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Conflict, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Gone, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.LengthRequired, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PreconditionFailed, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestEntityTooLarge, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestUriTooLong, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnsupportedMediaType, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ExpectationFailed, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MisdirectedRequest, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnprocessableEntity, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnprocessableContent, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Locked, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.FailedDependency, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UpgradeRequired, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PreconditionRequired, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.TooManyRequests, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnavailableForLegalReasons, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotImplemented, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.BadGateway, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ServiceUnavailable, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.GatewayTimeout, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.HttpVersionNotSupported, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.VariantAlsoNegotiates, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.InsufficientStorage, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.LoopDetected, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotExtended, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NetworkAuthenticationRequired, true)]
        #endregion
        #region Make sure all non-1xx codes are not included in the 1xx range and are NOT whitelisted
        [InlineData(new string[] { "1xx" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Created, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Accepted, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NonAuthoritativeInformation, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NoContent, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ResetContent, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PartialContent, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MultiStatus, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.AlreadyReported, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.IMUsed, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Ambiguous, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MultipleChoices, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Moved, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MovedPermanently, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Found, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Redirect, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RedirectMethod, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.SeeOther, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotModified, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UseProxy, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Unused, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RedirectKeepVerb, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.TemporaryRedirect, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PermanentRedirect, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.BadRequest, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Unauthorized, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PaymentRequired, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotFound, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MethodNotAllowed, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotAcceptable, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ProxyAuthenticationRequired, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestTimeout, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Conflict, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Gone, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.LengthRequired, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PreconditionFailed, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestEntityTooLarge, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestUriTooLong, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnsupportedMediaType, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ExpectationFailed, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MisdirectedRequest, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnprocessableEntity, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnprocessableContent, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Locked, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.FailedDependency, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UpgradeRequired, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PreconditionRequired, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.TooManyRequests, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnavailableForLegalReasons, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotImplemented, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.BadGateway, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ServiceUnavailable, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.GatewayTimeout, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.HttpVersionNotSupported, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.VariantAlsoNegotiates, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.InsufficientStorage, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.LoopDetected, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotExtended, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NetworkAuthenticationRequired, false)]
        #endregion
        #region Make sure all non-2xx codes are not included in the 2xx range and are NOT whitelisted
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Continue, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.SwitchingProtocols, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Processing, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.EarlyHints, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Ambiguous, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MultipleChoices, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Moved, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MovedPermanently, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Found, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Redirect, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RedirectMethod, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.SeeOther, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotModified, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UseProxy, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Unused, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RedirectKeepVerb, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.TemporaryRedirect, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PermanentRedirect, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.BadRequest, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Unauthorized, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PaymentRequired, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotFound, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MethodNotAllowed, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotAcceptable, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ProxyAuthenticationRequired, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestTimeout, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Conflict, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Gone, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.LengthRequired, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PreconditionFailed, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestEntityTooLarge, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestUriTooLong, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnsupportedMediaType, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ExpectationFailed, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MisdirectedRequest, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnprocessableEntity, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnprocessableContent, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Locked, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.FailedDependency, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UpgradeRequired, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PreconditionRequired, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.TooManyRequests, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnavailableForLegalReasons, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotImplemented, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.BadGateway, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ServiceUnavailable, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.GatewayTimeout, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.HttpVersionNotSupported, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.VariantAlsoNegotiates, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.InsufficientStorage, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.LoopDetected, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotExtended, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NetworkAuthenticationRequired, false)]
        #endregion
        #region Make sure all non-3xx codes are not included in the 3xx range and are NOT whitelisted
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Continue, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.SwitchingProtocols, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Processing, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.EarlyHints, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Created, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Accepted, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NonAuthoritativeInformation, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NoContent, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ResetContent, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PartialContent, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MultiStatus, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.AlreadyReported, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.IMUsed, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.BadRequest, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Unauthorized, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PaymentRequired, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotFound, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MethodNotAllowed, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotAcceptable, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ProxyAuthenticationRequired, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestTimeout, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Conflict, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Gone, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.LengthRequired, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PreconditionFailed, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestEntityTooLarge, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestUriTooLong, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnsupportedMediaType, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ExpectationFailed, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MisdirectedRequest, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnprocessableEntity, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnprocessableContent, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Locked, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.FailedDependency, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UpgradeRequired, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PreconditionRequired, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.TooManyRequests, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnavailableForLegalReasons, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotImplemented, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.BadGateway, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ServiceUnavailable, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.GatewayTimeout, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.HttpVersionNotSupported, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.VariantAlsoNegotiates, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.InsufficientStorage, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.LoopDetected, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotExtended, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NetworkAuthenticationRequired, false)]
        #endregion
        #region Make sure all non-4xx codes are not included in the 4xx range and are NOT whitelisted
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Continue, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.SwitchingProtocols, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Processing, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.EarlyHints, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Created, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Accepted, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NonAuthoritativeInformation, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NoContent, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ResetContent, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PartialContent, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MultiStatus, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.AlreadyReported, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.IMUsed, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Ambiguous, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MultipleChoices, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Moved, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MovedPermanently, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Found, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Redirect, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RedirectMethod, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.SeeOther, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotModified, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UseProxy, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Unused, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RedirectKeepVerb, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.TemporaryRedirect, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PermanentRedirect, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotImplemented, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.BadGateway, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ServiceUnavailable, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.GatewayTimeout, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.HttpVersionNotSupported, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.VariantAlsoNegotiates, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.InsufficientStorage, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.LoopDetected, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotExtended, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NetworkAuthenticationRequired, false)]
        #endregion
        #region Make sure all non-5xx codes are not included in the 5xx range and are NOT whitelisted
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Continue, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.SwitchingProtocols, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Processing, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.EarlyHints, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Created, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Accepted, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NonAuthoritativeInformation, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NoContent, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ResetContent, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PartialContent, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MultiStatus, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.AlreadyReported, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.IMUsed, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Ambiguous, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MultipleChoices, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Moved, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MovedPermanently, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Found, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Redirect, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RedirectMethod, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.SeeOther, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotModified, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UseProxy, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Unused, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RedirectKeepVerb, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.TemporaryRedirect, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PermanentRedirect, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.BadRequest, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Unauthorized, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PaymentRequired, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotFound, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MethodNotAllowed, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotAcceptable, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ProxyAuthenticationRequired, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestTimeout, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Conflict, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Gone, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.LengthRequired, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PreconditionFailed, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestEntityTooLarge, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestUriTooLong, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnsupportedMediaType, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ExpectationFailed, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MisdirectedRequest, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnprocessableEntity, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnprocessableContent, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Locked, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.FailedDependency, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UpgradeRequired, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PreconditionRequired, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.TooManyRequests, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnavailableForLegalReasons, false)]
        #endregion
        #region Are codes included in the correct ranges and therefore whitelisted? (Multiple Ranges)
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Continue, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.SwitchingProtocols, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Processing, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.EarlyHints, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Created, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Accepted, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.NonAuthoritativeInformation, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.NoContent, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.ResetContent, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.PartialContent, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.MultiStatus, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.AlreadyReported, true)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.IMUsed, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Ambiguous, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.MultipleChoices, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Moved, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.MovedPermanently, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Found, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Redirect, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.RedirectMethod, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.SeeOther, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.NotModified, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.UseProxy, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Unused, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.RedirectKeepVerb, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.TemporaryRedirect, true)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.PermanentRedirect, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.BadRequest, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Unauthorized, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.PaymentRequired, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.NotFound, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.MethodNotAllowed, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.NotAcceptable, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.ProxyAuthenticationRequired, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestTimeout, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Conflict, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Gone, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.LengthRequired, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.PreconditionFailed, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestEntityTooLarge, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestUriTooLong, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnsupportedMediaType, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.ExpectationFailed, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.MisdirectedRequest, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnprocessableEntity, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnprocessableContent, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Locked, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.FailedDependency, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UpgradeRequired, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.PreconditionRequired, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.TooManyRequests, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, true)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnavailableForLegalReasons, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.NotImplemented, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.BadGateway, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.ServiceUnavailable, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.GatewayTimeout, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.HttpVersionNotSupported, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.VariantAlsoNegotiates, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.InsufficientStorage, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.LoopDetected, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.NotExtended, true)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.NetworkAuthenticationRequired, true)]
        #endregion
        #region Are codes included in the correct ranges and therefore whitelisted? (Case insensitivity)
        [InlineData(new string[] { "1XX" }, HttpStatusCode.Continue, true)]
        [InlineData(new string[] { "1XX" }, HttpStatusCode.SwitchingProtocols, true)]
        [InlineData(new string[] { "1XX" }, HttpStatusCode.Processing, true)]
        [InlineData(new string[] { "1XX" }, HttpStatusCode.EarlyHints, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.Created, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.Accepted, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.NonAuthoritativeInformation, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.NoContent, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.ResetContent, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.PartialContent, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.MultiStatus, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.AlreadyReported, true)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.IMUsed, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Ambiguous, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.MultipleChoices, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Moved, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.MovedPermanently, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Found, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Redirect, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.RedirectMethod, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.SeeOther, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.NotModified, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.UseProxy, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Unused, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.RedirectKeepVerb, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.TemporaryRedirect, true)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.PermanentRedirect, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.BadRequest, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Unauthorized, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.PaymentRequired, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.NotFound, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.MethodNotAllowed, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.NotAcceptable, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.ProxyAuthenticationRequired, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestTimeout, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Conflict, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Gone, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.LengthRequired, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.PreconditionFailed, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestEntityTooLarge, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestUriTooLong, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnsupportedMediaType, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestedRangeNotSatisfiable, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.ExpectationFailed, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.MisdirectedRequest, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnprocessableEntity, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnprocessableContent, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Locked, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.FailedDependency, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UpgradeRequired, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.PreconditionRequired, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.TooManyRequests, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestHeaderFieldsTooLarge, true)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnavailableForLegalReasons, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.NotImplemented, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.BadGateway, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.ServiceUnavailable, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.GatewayTimeout, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.HttpVersionNotSupported, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.VariantAlsoNegotiates, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.InsufficientStorage, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.LoopDetected, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.NotExtended, true)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.NetworkAuthenticationRequired, true)]
        #endregion


        public void Whitelisting_with_Strings(string[] whitelist, HttpStatusCode statusCode, bool shouldPass)
        {
            HttpStatusCodeFilter filter = new HttpStatusCodeFilter(FilterType.Whitelist, whitelist);
            Assert.True(filter.PassesFilter(statusCode) == shouldPass);
        }

        [Theory]
        [InlineData(new string[] { "200", "403" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "200", "403" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "200", "403" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(null, HttpStatusCode.OK, false)] // a null blacklist means "everything is blacklisted"
        [InlineData(null, HttpStatusCode.InternalServerError, false)] // a null blacklist means "everything is blacklisted"
        [InlineData(new string[] { }, HttpStatusCode.OK, true)] // an empty blacklist means "nothing is blacklisted"
        #region Are codes included in the correct ranges and therefore blacklisted?
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Continue, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.SwitchingProtocols, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Processing, false)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.EarlyHints, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Created, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Accepted, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NonAuthoritativeInformation, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NoContent, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ResetContent, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PartialContent, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MultiStatus, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.AlreadyReported, false)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.IMUsed, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Ambiguous, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MultipleChoices, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Moved, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MovedPermanently, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Found, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Redirect, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RedirectMethod, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.SeeOther, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotModified, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UseProxy, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Unused, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RedirectKeepVerb, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.TemporaryRedirect, false)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PermanentRedirect, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.BadRequest, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Unauthorized, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PaymentRequired, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotFound, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MethodNotAllowed, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotAcceptable, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ProxyAuthenticationRequired, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestTimeout, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Conflict, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Gone, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.LengthRequired, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PreconditionFailed, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestEntityTooLarge, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestUriTooLong, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnsupportedMediaType, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ExpectationFailed, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MisdirectedRequest, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnprocessableEntity, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnprocessableContent, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Locked, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.FailedDependency, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UpgradeRequired, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PreconditionRequired, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.TooManyRequests, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, false)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UnavailableForLegalReasons, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotImplemented, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.BadGateway, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ServiceUnavailable, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.GatewayTimeout, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.HttpVersionNotSupported, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.VariantAlsoNegotiates, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.InsufficientStorage, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.LoopDetected, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotExtended, false)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NetworkAuthenticationRequired, false)]
        #endregion
        #region Make sure all non-1xx codes are not included in the 1xx range and are NOT blacklisted
        [InlineData(new string[] { "1xx" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Created, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Accepted, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NonAuthoritativeInformation, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NoContent, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ResetContent, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PartialContent, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MultiStatus, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.AlreadyReported, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.IMUsed, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Ambiguous, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MultipleChoices, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Moved, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MovedPermanently, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Found, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Redirect, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RedirectMethod, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.SeeOther, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotModified, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UseProxy, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Unused, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RedirectKeepVerb, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.TemporaryRedirect, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PermanentRedirect, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.BadRequest, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Unauthorized, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PaymentRequired, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotFound, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MethodNotAllowed, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotAcceptable, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ProxyAuthenticationRequired, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestTimeout, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Conflict, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Gone, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.LengthRequired, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PreconditionFailed, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestEntityTooLarge, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestUriTooLong, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnsupportedMediaType, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ExpectationFailed, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.MisdirectedRequest, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnprocessableEntity, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnprocessableContent, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.Locked, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.FailedDependency, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UpgradeRequired, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.PreconditionRequired, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.TooManyRequests, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.UnavailableForLegalReasons, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotImplemented, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.BadGateway, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.ServiceUnavailable, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.GatewayTimeout, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.HttpVersionNotSupported, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.VariantAlsoNegotiates, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.InsufficientStorage, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.LoopDetected, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NotExtended, true)]
        [InlineData(new string[] { "1xx" }, HttpStatusCode.NetworkAuthenticationRequired, true)]
        #endregion
        #region Make sure all non-2xx codes are not included in the 2xx range and are NOT blacklisted
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Continue, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.SwitchingProtocols, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Processing, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.EarlyHints, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Ambiguous, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MultipleChoices, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Moved, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MovedPermanently, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Found, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Redirect, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RedirectMethod, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.SeeOther, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotModified, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UseProxy, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Unused, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RedirectKeepVerb, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.TemporaryRedirect, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PermanentRedirect, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.BadRequest, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Unauthorized, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PaymentRequired, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotFound, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MethodNotAllowed, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotAcceptable, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ProxyAuthenticationRequired, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestTimeout, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Conflict, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Gone, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.LengthRequired, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PreconditionFailed, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestEntityTooLarge, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestUriTooLong, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnsupportedMediaType, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ExpectationFailed, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.MisdirectedRequest, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnprocessableEntity, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnprocessableContent, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.Locked, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.FailedDependency, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UpgradeRequired, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.PreconditionRequired, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.TooManyRequests, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.UnavailableForLegalReasons, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotImplemented, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.BadGateway, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.ServiceUnavailable, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.GatewayTimeout, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.HttpVersionNotSupported, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.VariantAlsoNegotiates, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.InsufficientStorage, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.LoopDetected, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NotExtended, true)]
        [InlineData(new string[] { "2xx" }, HttpStatusCode.NetworkAuthenticationRequired, true)]
        #endregion
        #region Make sure all non-3xx codes are not included in the 3xx range and are NOT blacklisted
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Continue, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.SwitchingProtocols, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Processing, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.EarlyHints, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Created, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Accepted, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NonAuthoritativeInformation, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NoContent, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ResetContent, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PartialContent, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MultiStatus, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.AlreadyReported, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.IMUsed, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.BadRequest, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Unauthorized, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PaymentRequired, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotFound, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MethodNotAllowed, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotAcceptable, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ProxyAuthenticationRequired, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestTimeout, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Conflict, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Gone, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.LengthRequired, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PreconditionFailed, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestEntityTooLarge, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestUriTooLong, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnsupportedMediaType, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ExpectationFailed, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.MisdirectedRequest, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnprocessableEntity, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnprocessableContent, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.Locked, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.FailedDependency, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UpgradeRequired, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.PreconditionRequired, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.TooManyRequests, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.UnavailableForLegalReasons, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotImplemented, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.BadGateway, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.ServiceUnavailable, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.GatewayTimeout, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.HttpVersionNotSupported, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.VariantAlsoNegotiates, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.InsufficientStorage, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.LoopDetected, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NotExtended, true)]
        [InlineData(new string[] { "3xx" }, HttpStatusCode.NetworkAuthenticationRequired, true)]
        #endregion
        #region Make sure all non-4xx codes are not included in the 4xx range and are NOT blacklisted
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Continue, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.SwitchingProtocols, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Processing, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.EarlyHints, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Created, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Accepted, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NonAuthoritativeInformation, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NoContent, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ResetContent, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PartialContent, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MultiStatus, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.AlreadyReported, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.IMUsed, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Ambiguous, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MultipleChoices, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Moved, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.MovedPermanently, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Found, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Redirect, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RedirectMethod, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.SeeOther, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotModified, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.UseProxy, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.Unused, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.RedirectKeepVerb, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.TemporaryRedirect, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.PermanentRedirect, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.InternalServerError, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotImplemented, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.BadGateway, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.ServiceUnavailable, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.GatewayTimeout, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.HttpVersionNotSupported, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.VariantAlsoNegotiates, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.InsufficientStorage, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.LoopDetected, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NotExtended, true)]
        [InlineData(new string[] { "4xx" }, HttpStatusCode.NetworkAuthenticationRequired, true)]
        #endregion
        #region Make sure all non-5xx codes are not included in the 5xx range and are NOT blacklisted
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Continue, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.SwitchingProtocols, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Processing, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.EarlyHints, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.OK, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Created, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Accepted, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NonAuthoritativeInformation, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NoContent, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ResetContent, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PartialContent, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MultiStatus, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.AlreadyReported, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.IMUsed, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Ambiguous, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MultipleChoices, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Moved, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MovedPermanently, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Found, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Redirect, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RedirectMethod, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.SeeOther, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotModified, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UseProxy, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Unused, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RedirectKeepVerb, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.TemporaryRedirect, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PermanentRedirect, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.BadRequest, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Unauthorized, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PaymentRequired, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Forbidden, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotFound, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MethodNotAllowed, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.NotAcceptable, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ProxyAuthenticationRequired, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestTimeout, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Conflict, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Gone, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.LengthRequired, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PreconditionFailed, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestEntityTooLarge, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestUriTooLong, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnsupportedMediaType, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.ExpectationFailed, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.MisdirectedRequest, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnprocessableEntity, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnprocessableContent, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.Locked, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.FailedDependency, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UpgradeRequired, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.PreconditionRequired, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.TooManyRequests, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, true)]
        [InlineData(new string[] { "5xx" }, HttpStatusCode.UnavailableForLegalReasons, true)]
        #endregion
        #region Are codes included in the correct ranges and therefore blacklisted? (Multiple Ranges)
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Continue, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.SwitchingProtocols, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Processing, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.EarlyHints, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Created, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.Accepted, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.NonAuthoritativeInformation, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.NoContent, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.ResetContent, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.PartialContent, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.MultiStatus, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.AlreadyReported, false)]
        [InlineData(new string[] { "1xx", "2xx" }, HttpStatusCode.IMUsed, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Ambiguous, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.MultipleChoices, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Moved, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.MovedPermanently, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Found, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Redirect, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.RedirectMethod, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.SeeOther, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.NotModified, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.UseProxy, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.Unused, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.RedirectKeepVerb, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.TemporaryRedirect, false)]
        [InlineData(new string[] { "1xx", "3xx" }, HttpStatusCode.PermanentRedirect, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.BadRequest, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Unauthorized, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.PaymentRequired, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.NotFound, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.MethodNotAllowed, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.NotAcceptable, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.ProxyAuthenticationRequired, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestTimeout, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Conflict, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Gone, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.LengthRequired, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.PreconditionFailed, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestEntityTooLarge, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestUriTooLong, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnsupportedMediaType, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.ExpectationFailed, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.MisdirectedRequest, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnprocessableEntity, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnprocessableContent, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.Locked, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.FailedDependency, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UpgradeRequired, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.PreconditionRequired, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.TooManyRequests, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.RequestHeaderFieldsTooLarge, false)]
        [InlineData(new string[] { "1xx", "4xx" }, HttpStatusCode.UnavailableForLegalReasons, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.NotImplemented, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.BadGateway, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.ServiceUnavailable, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.GatewayTimeout, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.HttpVersionNotSupported, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.VariantAlsoNegotiates, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.InsufficientStorage, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.LoopDetected, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.NotExtended, false)]
        [InlineData(new string[] { "1xx", "5xx" }, HttpStatusCode.NetworkAuthenticationRequired, false)]
        #endregion
        #region Are codes included in the correct ranges and therefore blacklisted? (Case insensitivity)
        [InlineData(new string[] { "1XX" }, HttpStatusCode.Continue, false)]
        [InlineData(new string[] { "1XX" }, HttpStatusCode.SwitchingProtocols, false)]
        [InlineData(new string[] { "1XX" }, HttpStatusCode.Processing, false)]
        [InlineData(new string[] { "1XX" }, HttpStatusCode.EarlyHints, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.OK, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.Created, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.Accepted, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.NonAuthoritativeInformation, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.NoContent, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.ResetContent, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.PartialContent, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.MultiStatus, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.AlreadyReported, false)]
        [InlineData(new string[] { "2XX" }, HttpStatusCode.IMUsed, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Ambiguous, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.MultipleChoices, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Moved, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.MovedPermanently, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Found, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Redirect, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.RedirectMethod, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.SeeOther, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.NotModified, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.UseProxy, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.Unused, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.RedirectKeepVerb, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.TemporaryRedirect, false)]
        [InlineData(new string[] { "3XX" }, HttpStatusCode.PermanentRedirect, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.BadRequest, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Unauthorized, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.PaymentRequired, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Forbidden, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.NotFound, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.MethodNotAllowed, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.NotAcceptable, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.ProxyAuthenticationRequired, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestTimeout, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Conflict, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Gone, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.LengthRequired, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.PreconditionFailed, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestEntityTooLarge, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestUriTooLong, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnsupportedMediaType, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestedRangeNotSatisfiable, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.ExpectationFailed, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.MisdirectedRequest, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnprocessableEntity, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnprocessableContent, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.Locked, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.FailedDependency, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UpgradeRequired, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.PreconditionRequired, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.TooManyRequests, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.RequestHeaderFieldsTooLarge, false)]
        [InlineData(new string[] { "4XX" }, HttpStatusCode.UnavailableForLegalReasons, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.InternalServerError, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.NotImplemented, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.BadGateway, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.ServiceUnavailable, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.GatewayTimeout, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.HttpVersionNotSupported, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.VariantAlsoNegotiates, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.InsufficientStorage, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.LoopDetected, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.NotExtended, false)]
        [InlineData(new string[] { "5XX" }, HttpStatusCode.NetworkAuthenticationRequired, false)]
        #endregion
        public void Blacklisting_with_Strings(string[] blacklist, HttpStatusCode statusCode, bool shouldPass)
        {
            HttpStatusCodeFilter filter = new HttpStatusCodeFilter(FilterType.Blacklist, blacklist);
            Assert.True(filter.PassesFilter(statusCode) == shouldPass);
        }

        [Fact]
        public void Serialization() // just make sure the type can be serialized and deserialized accurately.
        {
            var statusCodeFilter = new HttpStatusCodeFilter(FilterType.Blacklist, new HttpStatusCode[] { HttpStatusCode.OK, HttpStatusCode.Forbidden });

            string j = JsonSerializer.Serialize(statusCodeFilter);
            var deserialized = JsonSerializer.Deserialize<HttpStatusCodeFilter>(j);
            Assert.NotNull(deserialized);
            Assert.Equal(deserialized.FilterType, statusCodeFilter.FilterType);
            Assert.Equal(deserialized.Values, statusCodeFilter.Values);
        }
    }
}
