FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY *.sln ./
COPY demos/ApiGateway.Web/ApiGateway.Web.csproj demos/ApiGateway.Web/
COPY src/Ocelot/Ocelot.csproj src/Ocelot/

RUN dotnet restore

COPY . .
WORKDIR /src/demos/ApiGateway.Web
RUN dotnet add package BuildBundlerMinifier
RUN dotnet restore
RUN dotnet bundle
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
VOLUME /app/Configurations

ENTRYPOINT ["dotnet", "ApiGateway.Web.dll"]
