# call from ocelot repo root with
# docker build --build-arg OCELOT_NUTGET_API_KEY=$OCELOT_NUTGET_API_KEY --build-arg OCELOT_GITHUB_API_KEY=$OCELOT_GITHUB_API_KEY -f ./docker/Dockerfile.release .

FROM mijitt0m/ocelot-build:0.0.1

ARG OCELOT_GITHUB_API_KEY
ARG OCELOT_NUTGET_API_KEY

ENV OCELOT_NUTGET_API_KEY=$OCELOT_NUTGET_API_KEY
ENV OCELOT_GITHUB_API_KEY=$OCELOT_GITHUB_API_KEY

WORKDIR /src

COPY ./. .

RUN chmod u+x build.sh

RUN make release