# call from ocelot repo root with
# docker build --build-arg OCELOT_COVERALLS_TOKEN=$OCELOT_COVERALLS_TOKEN -f ./docker/Dockerfile.build .
FROM mijitt0m/ocelot-build:0.0.1

ARG OCELOT_COVERALLS_TOKEN

ENV OCELOT_COVERALLS_TOKEN=$OCELOT_COVERALLS_TOKEN

WORKDIR /src

COPY ./. .

RUN chmod u+x build.sh

RUN make build