name: Develop
on:
  push:
    branches:
      - develop
      # - 'release/**' # for testing purposes
jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu, macos, windows]
        framework: [net10]
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: SH-scripts
      id: scripts
      run: |
        chmod +x .github/steps/*.sh
        ls -l .github/steps/*.sh
        frm="${{ matrix.framework }}"
        clean="${frm#net}"
        echo "version=$clean" >> $GITHUB_OUTPUT
    - name: Check .NET ${{ steps.scripts.outputs.version }}
      id: checkdotnet
      run: ./.github/steps/check-dotnet.sh ${{ steps.scripts.outputs.version }}
    - name: Setup .NET ${{ steps.scripts.outputs.version }}
      # if: steps.checkdotnet.outputs.CHECKDOTNET_installed == 'false'
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.scripts.outputs.version }}.x
        cache: true
        cache-dependency-path: |
          samples/**/packages.lock.json
          src/**/packages.lock.json
          test/**/packages.lock.json
    - name: .NET Info
      run: dotnet --info
    - name: Add DNS-records
      run: ./.github/steps/${{ matrix.os }}.add-dns-records.sh  
    - name: Install certificate
      run: ./.github/steps/${{ matrix.os }}.install-certificate.sh
    - name: Restore
      run: dotnet restore --locked-mode ./Ocelot.slnx
    - name: Build
      run: dotnet build --no-restore ./Ocelot.slnx --framework ${{ matrix.framework }}.0          
    - name: Unit Tests
      run: dotnet test --no-restore --no-build --verbosity normal --framework ${{ matrix.framework }}.0 --project ./unit/Ocelot.UnitTests.csproj
    - name: Acceptance Tests
      run: dotnet test --no-restore --no-build --verbosity minimal --framework ${{ matrix.framework }}.0 --project ./acceptance/Ocelot.Acceptance.csproj

  coverage:
    needs: build
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        # with:
        #   fetch-depth: 0
      - name: SH-scripts executable
        run: chmod +x .github/steps/*.sh
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
          cache: true
          cache-dependency-path: |
            samples/**/packages.lock.json
            src/**/packages.lock.json
            test/**/packages.lock.json
      - name: .NET Info
        run: dotnet --info
      # Not required for unit testing (but it is for acceptance testing)
      # - name: Add DNS-records
      #   run: ./.github/steps/ubuntu.add-dns-records.sh  
      # - name: Install certificate
      #   run: ./.github/steps/ubuntu.install-certificate.sh
      - name: Restore
        run: dotnet restore --locked-mode ./Ocelot.slnx
      - name: Build
        run: dotnet build --no-restore ./Ocelot.slnx --framework net10.0
      - name: Unit Tests
        run: |
          dotnet test --no-restore --no-build --verbosity normal --framework net10.0 --project ./unit/Ocelot.UnitTests.csproj \
            --coverlet --coverlet-include "[Ocelot*]*" --coverlet-exclude "[Ocelot.Testing]*"
      # - name: Acceptance Tests
      #   run: dotnet test --no-restore --no-build --verbosity minimal --framework net10.0 --project ./acceptance/Ocelot.Acceptance.csproj
      - name: Coverage files
        id: coverage
        run: ./.github/steps/prepare-coveralls.sh # net10.0 Debug
      - name: Coveralls
        if: steps.coverage.outputs.COVERAGE_file_exists == 'true'
        uses: coverallsapp/github-action@v2
        with:
          # fail-on-error: false
          file: ${{ steps.coverage.outputs.COVERAGE_file }}
        continue-on-error: true
      - name: Codecov
        if: steps.coverage.outputs.COVERAGE_file_exists == 'true'
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.coverage.outputs.COVERAGE_file }}
          flags: unit
        # continue-on-error: true
