name: Release
on:
  push:
    branches:
      - main
      - 'release/24.**'
jobs:
  # Matrix build job having 2 dimensions (os, .NET ver)
  build:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu, macos, windows]
        framework: [net8, net9, net10]
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: SH-scripts
      id: scripts
      run: |
        chmod +x .github/steps/*.sh
        ls -l .github/steps/*.sh
        frm="${{ matrix.framework }}"
        clean="${frm#net}"
        echo "version=$clean" >> $GITHUB_OUTPUT
    - name: Check .NET ${{ steps.scripts.outputs.version }}
      id: checkdotnet
      run: ./.github/steps/check-dotnet.sh ${{ steps.scripts.outputs.version }}
    - name: Setup .NET ${{ steps.scripts.outputs.version }}
      # if: steps.checkdotnet.outputs.CHECKDOTNET_installed == 'false'
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.scripts.outputs.version }}.x
        cache: true
        cache-dependency-path: |
          samples/**/packages.lock.json
          src/**/packages.lock.json
          test/**/packages.lock.json
    - name: .NET Info
      run: dotnet --info
    - name: Add DNS-records
      run: ./.github/steps/${{ matrix.os }}.add-dns-records.sh  
    - name: Install certificate
      run: ./.github/steps/${{ matrix.os }}.install-certificate.sh
    - name: Restore
      run: dotnet restore --locked-mode ./Ocelot.slnx
    - name: Build
      run: dotnet build --no-restore ./Ocelot.slnx --framework ${{ matrix.framework }}.0          
    - name: Unit Tests
      run: dotnet test --no-restore --no-build --verbosity minimal --framework ${{ matrix.framework }}.0 --settings coverlet.runsettings ./test/Ocelot.UnitTests/Ocelot.UnitTests.csproj
    - name: Acceptance Tests
      run: dotnet test --no-restore --no-build --verbosity minimal --framework ${{ matrix.framework }}.0 --settings coverlet.runsettings ./test/Ocelot.AcceptanceTests/Ocelot.AcceptanceTests.csproj

  release-cake:
    needs: build
    runs-on: ubuntu-latest
    environment: build.cake # TODO Rename to Release
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Env Variables
        env:
          # CAKE_RELEASE_MYVAR: ${{ vars.CAKE_RELEASE_MYVAR }}
          # TEMP_KEY: ${{ secrets.TEMP_KEY }} # leaked secret LoL
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "github context >>>" # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
          echo "$GITHUB_CONTEXT"
          echo "<<<"
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: SH-scripts executable
        run: |
          chmod +x .github/steps/*.sh
          ls -l .github/steps/*.sh
      - name: Check .NET 10
        id: checkdotnet
        run: ./.github/steps/check-dotnet.sh 10
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
          cache: true
          cache-dependency-path: |
            samples/**/packages.lock.json
            src/**/packages.lock.json
            test/**/packages.lock.json
      - name: Cake Build
        uses: cake-build/cake-action@v3
        with:
          target: Release
        env:
          OCELOT_GITHUB_API_KEY: ${{ secrets.OCELOT_GITHUB_API_KEY }}
          OCELOT_NUGET_API_KEY_2025: ${{ secrets.OCELOT_NUGET_API_KEY_2025 }}
          # COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Coverage files
        id: coverage
        run: ./.github/steps/prepare-coveralls.sh
      - name: Coveralls
        if: steps.coverage.outputs.COVERAGE_file_exists == 'true'
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ steps.coverage.outputs.COVERAGE_file }}
          compare-ref: main
        continue-on-error: true
      - name: Codecov
        if: steps.coverage.outputs.COVERAGE_file_exists == 'true'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ThreeMammals/Ocelot
          fail_ci_if_error: true
          files: ${{ steps.coverage.outputs.COVERAGE_file }}
          flags: unit
        continue-on-error: true
